const MainMenu = [
    {
        id : 1,
        main_img : "../images/main1.jpg",
        title : "Doryain",
        watch : "566k",
        time : "2 day",
        short_img : "../images/short1.jpg",
    },
    {
        id : 2,
        main_img : "../images/main2.jpg",
        title : "Farhad",
        watch : "344k",
        time : "1 year",
        short_img : "../images/short2.jpg",
    },
    {
        id : 3,
        main_img : "../images/main3.jpg",
        title : "Feroz",
        watch : "2m",
        time : "5 day",
        short_img : "../images/short3.jpg",
    },
    {
        id : 4,
        main_img : "../images/main4.jpg",
        title : "Almas",
        watch : "333k",
        time : "1.4 day",
        short_img : "../images/short4.jpg",
    },
    {
        id : 5,
        main_img : "../images/main5.jpg",
        title : "Bunyan",
        watch : "4k",
        time : "5 min",
        short_img : "../images/short5.jpg",
    },
    {
        id : 6,
        main_img : "../images/main6.jpg",
        title : "Reeza",
        watch : "765k",
        time : "56 h",
        short_img : "../images/short6.jpg",
    },
    {
        id : 7,
        main_img : "../images/main7.jpg",
        title : "Dhoom",
        watch : "12k",
        time : "23 s",
        short_img : "../images/short7.jpg",
    },
    {
        id : 8,
        main_img : "../images/main8.jpg",
        title : "Shah",
        watch : "23m",
        time : "7 s",
        short_img : "../images/short8.jpg",
    },
    {
        id : 9,
        main_img : "../images/main9.jpg",
        title : "Rustam",
        watch : "256 K",
        time : "34 week",
        short_img : "../images/short9.jpg",
    },
    {
        id : 10,
        main_img : "../images/main10.jpg",
        title : "Malik",
        watch : "76k",
        time : "34 Min",
        short_img : "../images/short10.jpg",
    },
    {
        id : 11,
        main_img : "../images/main11.jpg",
        title : "Rexwan",
        watch : "40k",
        time : "20 day",
        short_img : "../images/short11.jpg",
    },
    {
        id : 12,
        main_img : "../images/main12.jpg",
        title : "Abdul",
        watch : "87799",
        time : "12 day",
        short_img : "../images/short12.jpg",
    },
    {
        id : 13,
        main_img : "../images/main13.jpg",
        title : "Jaaan",
        watch : "87 K",
        time : "4 h",
        short_img : "../images/short13.jpg",
    },
    {
        id : 14,
        main_img : "../images/main14.jpg",
        title : "Muhammad",
        watch : "98 K",
        time : "7 h",
        short_img : "../images/short14.jpg",
    },
    {
        id : 15,
        main_img : "../images/main15.jpg",
        title : "Haseb",
        watch : "2m",
        time : "10 day",
        short_img : "../images/short15.jpg",
    },
    {
        id : 16,
        main_img : "../images/main16.jpg",
        title : "Naqib",
        watch : "12m",
        time : "14 h",
        short_img : "../images/short16.jpg",
    },
    {
        id : 17,
        main_img : "../images/main17.jpg",
        title : "Suhbat",
        watch : "76M",
        time : "19 h",
        short_img : "../images/short17.jpg",
    },
    {
        id : 18,
        main_img : "../images/main18.jpg",
        title : "Burhan",
        watch : "87k",
        time : "34 week",
        short_img : "../images/short18.jpg",
    },
    {
        id : 19,
        main_img : "../images/main19.jpg",
        title : "dDaay",
        watch : "455k",
        time : "3 S",
        short_img : "../images/short19.jpg",
    },
    {
        id : 20,
        main_img : "../images/main20.jpg",
        title : "Alhaj",
        watch : "677k",
        time : "20 h",
        short_img : "../images/short20.jpg",
    },
];
export default MainMenu;